name:                record5
version:             0.0.0.1
github:              "kazark/record5"
license:             MIT
author:              "Keith Pinson"
maintainer:          "kazark@zoho.com"
copyright:           "2019 (c) Keith Pinson"

extra-source-files:
- README.md

description:         Just a little exercise.

dependencies:
- base >= 4.7 && < 5
- filepath

library:
  source-dirs: src

executables:
  record5-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - record5

tests:
  record5-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - record5
